adaptation_method: T2A
adapter_config:
  steps: 1
  episodic: false
  # adapter optim
  optimizer: Adam
  optimizer_config:
    lr: 1e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
  l1_lambda: 0.0
  num_classes: 2
  entropy_fn: entropy
  noise_type: bernoulli
  psi: 0.01
  gamma: 2.0
  alpha: 1.0
  beta: 1.0

